### ISSUE TITLE
License implications

### ISSUE THREAD

**Issue by jowr** [bovender/ExcelAddinInstaller#1]
Thank you for this useful collection of configuration files and scripts. I think about using your package for a commercial Excel-plugin that I develop at my day job, but I am concerned the GPL licensing terms since I cannot publish the source code of the library (DLL) that I would like to install. 
Could you please clarify how you think the GPL should be treated in this case? Can I use your package and only publish my modified Inno Setup script or was your intention with the GPL to force users to publish all the source code of the packaged applications/libraries? 
I am not a lawyer and I would therefore appreciate if you could express your understanding of the licensing scheme here. Maybe you can also add your answer to the `readme.md`.

**Comment by bovender** [comment]
Hi Jorrit, thank you so much for your interest in this little script. It is my intention to make it available for free, while preventing others to 'steal' my intellectual property by claiming it is theirs and protecting myself from liability claims to the greatest possible extent.

Of course I do want you to use it for your projects, even if it is a commercial project, and it is my understanding that the GPL does not stand in the way. After all, you are not linking your DLL against the installer script! Please, go ahead. If you or your company need additional reassurance, let's think about a way (can I license it to you under a different license?).

By the way, I have a VstoAddinInstaller in the works that can be used to distribute VSTO add-ins, and this will be probably licensed under the Apache License 2.0, which is not as restrictive as the GPL.

**Comment by jowr** [comment]
Thank you for the swift response. I am glad to hear that your understanding of the case is well aligned with my own interpretation of the licensing question. I, however, only wanted to make sure that I am not violating your intentions (no commercial use, for example) even though the legal situation might permit this. 
Well, thanks again and I will make sure that we put a copyright note and a back link to this repository in the documentation, if we ever go for this solution. I am not sure about our installer script, but I might just fork the repo and file a pull request in case I add anything interesting to the script.

**Comment by bovender** [comment]
I've uploaded my [VstoAddinInstaller](https://github.com/bovender/VstoAddinInstaller) which I would definitively recommend to look into if you are deploying VSTO add-ins. I'm using it for two of my projects right now.
