### ISSUE TITLE
Excel 2016

### ISSUE THREAD

**Issue by jowr** [bovender/ExcelAddinInstaller#3]
Hi, I am not an expert in Excel, but can Office 2016 support be added by simply changing `MaxExcelVersion = 15;` to `MaxExcelVersion = 16;` in [inc/code.iss#L25](https://github.com/bovender/ExcelAddinInstaller/blob/master/inc/code.iss#L25)?

**Comment by bovender** [comment]
Yes, that's right. You can also just set the value to 20, for example.

**Comment by bovender** [comment]
See 92f4b98ed608707cab81dc7e2a1305d64c6fce98.

**Comment by jowr** [comment]
Thank you for the swift reply and fix.
