### ISSUE TITLE
Compatibility with Office (365?) installed from Microsoft Store

### ISSUE THREAD

**Issue by JulienMaille** [bovender/ExcelAddinInstaller#7]
It seems registry and disk paths are quite different in that case. I can help if needed.
```
function IsExcelVersionInstalled(MinVer: integer; MaxVer: integer): boolean;
var
    xl: integer;
begin
    for xl := MinVer to MaxVer do
        if RegKeyExists(HKEY_CURRENT_USER,
        'Software\Microsoft\Office\'+IntToStr(xl)+'.0\Excel\Options') then
        begin
            Result := true;
        end
        else
        begin
            log('Looking for Windows store Office'); 
      if RegKeyExists(HKEY_LOCAL_MACHINE,
          'Software\Microsoft\Office\'+IntToStr(xl)+'.0\Common') then
          begin
              Result := true;
          end
    end;
    Log('IsExcelVersionInstalled('+IntToStr(MinVer)+', '+
        IntToStr(MaxVer)+') returns '+BoolToStr(result));
end;
```

**Comment by bovender** [comment]
Thank, I appreciate it. Do you happen to be able to test this on different machines? Just asking because in my experience, Office-related registry keys are rather complex, and I want to make sure that this is universal?

**Comment by JulienMaille** [comment]
I tested on 2 machines (one desktop computer, one Microsoft Surface). More feedback would be appreciated.

**Comment by bovender** [comment]
Sorry, I never got around to following up on this. To be honest, I had totally forgotten that this issue still existed. Did you gather more experience with this patch?

**Comment by JulienMaille** [comment]
I'm sorry I could not test on more machines, most of the ones I tried had "regular" office installs.
